### ISSUE TITLE
Interpolate global variables in SQL block configuration

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1166]
When writing in the database or the schema in a SQL block, currently you hardcode the values.

You write the values in an input field shown below:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/1066980/195265215-97d49fd7-7c68-4ba9-a872-8ef98c5a8779.png">

This information gets written to the pipeline’s YAML file, in the block’s configuration. For example:
```yaml
blocks:
- all_upstream_blocks_executed: true
  configuration:
    data_provider: snowflake
    data_provider_profile: default
    data_provider_database: mage
    data_provider_schema: public
    export_write_policy: append
  executor_type: local_python
  language: sql
```

Instead of hardcoding, we should be able to interpolate any variable values using the handlebar syntax: `{{ var('env') }}` where `env` is the key we want to extract from the global variables.

So now, we can save SQL block configurations like this:
```yaml
blocks:
- all_upstream_blocks_executed: true
  configuration:
    data_provider: snowflake
    data_provider_profile: default
    data_provider_database: mage_{{ var('env') }}
    data_provider_schema: public_{{ var('env') }}
    export_write_policy: append
  executor_type: local_python
  language: sql
```

When a SQL block is executed, the database and schema are accessed here: https://github.com/mage-ai/mage-ai/blob/master/mage_ai/data_preparation/models/block/sql/__init__.py#L34

We should interpolate the variable values from the global variables into the database and schema values if the above syntax is present.
