### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by jpiedragil** [mage-ai/mage-ai#3467]
Path: /guides/load-api-data

I followed the ETL pipeline tutorial, but when I ran the Export data to PostgreSQL step, I got the following error:

![image](https://github.com/mage-ai/mage-ai/assets/20465277/958389af-48b7-49e9-84eb-8339bb44a53c)

The content of the io_config.yaml file is:

```
version: 0.1.1
default:
  POSTGRES_PORT: 5432
  POSTGRES_DBNAME: xyleviup
  POSTGRES_USER: xyleviup
  POSTGRES_PASSWORD: edSrMWH7Mww-lTKpp-jPHX9sYSNLy7LG
  POSTGRES_HOST: queenie.db.elephantsql.com
  POSTGRES_SCHEMA: elt_demo
```
