### ISSUE TITLE
Production deployment to AKS with persistent volume claim causes errors

### ISSUE THREAD

**Issue by WesAkers** [mage-ai/mage-ai#3582]
## Description

When deploying Mage to production in Azure on to Azure Kubernetes Service using the Helm chart, I encounter errors post-deployment where Mage cannot write to the SQLite database. On pod startup, it seems like Mage cannot create the tables it needs to in the SQLite mageai.db. This causes the Pipelines page of the Mage UI to show an error that it cannot find the table "pipeline_schedule". I'm not creating a bug ticket specifically because I'm not sure if this is truly a bug or if I have just misconfigured something with the PVC. There is no PVC claim example in the repo for AKS clusters (or at least I couldn't find it), only for ECS, so I did my best to set up what I thought would be necessary. I tried two different PVC claim variations, both shown below.

## Setup

- I have created an AKS cluster in the environment
- I have created an Azure Storage account in the environment
- I have created a persistent volume claim on the AKS cluster using the yaml below
- I have built and deployed a container image to Azure Container Registry
- I have deployed the image to the AKS cluster using the mage Helm chart

### Displayed on the Mage UI Pipelines page

```
(sqlite3.OperationalError) no such table: pipeline_schedule [SQL: SELECT a.created_at AS a_created_at, a.id AS a_id, a.name AS a_name, a.pipeline_uuid AS a_pipeline_uuid, a.schedule_interval AS a_schedule_interval, a.schedule_type AS a_schedule_type, a.start_time AS a_start_time, a.status AS a_status, a.updated_at AS a_updated_at FROM pipeline_schedule AS a WHERE a.pipeline_uuid IN (?, ?) AND (a.repo_path = ? OR a.repo_path IS NULL)] [parameters: ('availity_claim_status', 'example_pipeline', '/home/mage_code/yggdrasil')] (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### From k8s pod startup logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

...
...
...

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: 
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
)

]
```

## Persistent volume yaml

I tried two different ways to create the persistent volume. One was to statically create the storage account in Azure first, and the second was to dynamically let k8s create the resource through the pvc. Neither fixed the issue and the end result was the same set of errors. Here are the two versions of the pvc yaml I tried:

### v1

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yggdrasil-azurefile-sc
provisioner: kubernetes.io/azure-file

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yggdrasil-azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: yggdrasil-azurefile-sc
  azureFile:
    secretName: azure-secret
    shareName: a-fs-yggdrasil
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yggdrasil-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yggdrasil-azurefile-sc
  resources:
    requests:
      storage: 5Gi
```

### v2

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: yggdrasil-azurefile-sc
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
parameters:
  skuName: Premium_LRS

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yggdrasil-azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: yggdrasil-azurefile-sc
  azureFile:
    secretName: azure-secret
    shareName: a-fs-yggdrasil
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yggdrasil-azurefile-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: yggdrasil-azurefile-sc
  resources:
    requests:
      storage: 5Gi
```

## K8s cluster

This is what my cluster looks like if it matters.

```
> kubectl get all --namespace ns-yggdrasil
NAME                          READY   STATUS    RESTARTS   AGE
pod/mageai-77466cfccc-w7qh7   1/1     Running   0          20h

NAME             TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)          AGE
service/mageai   LoadBalancer   10.0.115.136   20.69.118.113   6789:32065/TCP   20h

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mageai   1/1     1            1           20h

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/mageai-77466cfccc   1         1         1       20h
```

## Musings

I have worked around this problem for now by standing up a PostgreSQL database and using that instead of the SQLite db, but I'm concerned that I do not have the pvc configured correctly, and so whatever other dependencies Mage has on that will cause failures down the line. I did ensure I was creating a file share in the Azure Storage account which supports the `ReadWriteMany` claim, so I believe that is correct, and it's obvious that Mage can at least write to that share because it does create the directory structure as well as the `mageai.db` file, so I'm confused as to the source of the deadlock. 

## P.S.

Sorry I'm a k8s newb, so if something is obviously wrong you can close this and tell me to read more. I appreciate you and this product - Mage is pretty great.
