### ISSUE TITLE
feat: Enable CI Build Caching for Next.js

### ISSUE THREAD

**Issue by mfreeman451** [mage-ai/mage-ai#4079]
**Is your feature request related to a problem? Please describe.**

An error occurs because a Next.js build was triggered in a continuous integration environment, but no cache was detected.

To improve build performance, Next.js saves a cache to .next/cache that is shared between builds.

To take advantage of this cache in Continuous Integration (CI) environments, our CI workflow will need to be configured to correctly persist the cache between builds.

https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching

Nextjs recommends we use the build cache to improve build performance.

**Describe the solution you'd like**

```
uses: actions/cache@v3
with:
  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
  path: |
    ~/.npm
    ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

**Describe alternatives you've considered**

N/A

**Additional context**

<img width="953" alt="Screenshot 2023-11-25 at 6 22 18 PM" src="https://github.com/mage-ai/mage-ai/assets/1821930/0e1bb7c6-086a-4f31-b1a8-24e8adab3f86">
