### ISSUE TITLE
Google Ads Source not retrieving data

### ISSUE THREAD

**Issue by Luishfs** [mage-ai/mage-ai#4093]
**Describe the bug**
User reported Google Ads Source does not seem to retrieve any data when syncing

Data Integration check-list:
- [X] Test Connection
- [X] Discover Streams
- [X] Pipeline Execution
- [ ] Data Inserted into Destination

User settings example:
```yaml
developer_token: "{{ mage_secret_var('GA_DEVELOPER_TOKEN') }}"
oauth_client_id: "{{ mage_secret_var('GA_OAUTH_CLIENT_ID') }}"
oauth_client_secret: "{{ mage_secret_var('GA_OAUTH_CLIENT_SECRET') }}"
refresh_token: "{{ mage_secret_var('GA_REFRESH_TOKEN') }}"
start_date: 2023-01-01T00:00:00Z
login_customer_ids:
  - customerId: "123456789"
    loginCustomerId: "123456789"
```

**Additional context**
Pipeline runs with Google Ads as a source and Snowflake as destination
