### ISSUE TITLE
Add the ability to dynamically select an io_config profile in a SQL Block

### ISSUE THREAD

**Issue by WesAkers** [mage-ai/mage-ai#4129]
**Is your feature request related to a problem? Please describe.**
When using a SQL Block, the only way to currently select an io_config profile is through the UI drop down menu. This is a problem when you want to run the same pipeline against different sources or targets because you can't dynamically select a config profile based on a pipeline variable like environment or customer.

**Describe the solution you'd like**
I would like to be able to dynamically select a config profile through some sort of statement or syntax in the SQL Block. It would be something similar to how we can do it in the Python blocks like:

```
config_path = path.join(get_repo_path(), 'io_config.yaml')
config_profile = kwargs['customer'] + "_" + kwargs['env'] + "_" + kwargs['database_config_profile']
```

**Describe alternatives you've considered**
I am trying to work around by either having config profiles pull the pipeline variable via the variable syntax or by switching the config profile values using environment variables. Neither of these work-arounds seem like very maintainable solutions to me.

Edit: You cannot reference pipeline variables in the io_config.yaml, and changing the environment variables works but having to do that 15 times per day because I'm running a pipeline for 15 different customers isn't really a good solution.

**Additional context**

**Comment by WesAkers** [comment]
Was poking around, and if I could do something in the pipeline metadata.yaml like so, where I am interpolating variables as part of the data_provider_profile, that would work I think:
```

- all_upstream_blocks_executed: false
  color: null
  configuration:
    data_provider: sqlserver
    data_provider_profile: "{{variables('customer')}}_dev_database"
    dbt: {}
    export_write_policy: append
    limit: 1000
    use_raw_sql: false
    
```
