### ISSUE TITLE
[BUG] Multi project platform

### ISSUE THREAD

**Issue by AbdulRafay** [mage-ai/mage-ai#4403]
### Mage version

v0.9.60

### Describe the bug

Ported and existing mage project to mage's new feature "Multi Project Platform"

Changes that i made. 

Created a new directory master_project and moved my existing project "demo_project" inside it
when i try to create a new pipeline, or edit and existing pipeline i get following error

`[Errno 2] No such file or directory: '/home/src/master_project/demo_project/master_project/platform_template/default_repo/data_exporters/data_exporter.py'`

i did not setup platfom_template but somehow it is trying to search in it. 

### To reproduce

docker-compose.yml

```
version: '3'
services:
  mageai:
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    image: mageai/mageai:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MAGE_DATABASE_CONNECTION_URL=postgresql://mageai:mageai_password@db:5432/mageai
      - USER_CODE_PATH=/home/src/${PROJECT_NAME}
      - ENV=${ENV}
      - ENABLE_PROJECT_PLATFORM=1
    ports:
      - 6789:6789
    depends_on:
      - db
    volumes:
      - .:/home/src/
      - mage_data:/root/.mage_data
    restart: on-failure:5

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=mageai
      - POSTGRES_PASSWORD=mageai_password
      - POSTGRES_DB=mageai
      - POSTGRESQL_PORT=5432
    ports:
      - 5439:5432
    volumes:
      - mageai_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  mageai_db_data:
  mage_data:

```

DockerFile

```
FROM mageai/mageai:latest

ARG PIP=pip3

ARG USER_CODE_PATH=/home/src/${PROJECT_NAME}

# Add Debian Bullseye repository
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list.d/bullseye.list
# Install OpenJDK 11
RUN apt-get update -y && \
    apt-get install -y openjdk-11-jdk

# Remove Debian Bullseye repository
RUN rm /etc/apt/sources.list.d/bullseye.list

RUN ${PIP} install pyspark


# Install dependencies for pyodbc, curl, and gnupg2 for keys
RUN apt-get update \
    && apt-get install -y gnupg2 curl unixodbc-dev

# Add the Microsoft SQL Server ODBC Driver repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Install the ODBC Driver for SQL Server
RUN apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 \
    && rm -rf /var/lib/apt/lists/*

# Note: this overwrites the requirements.txt file in your new project on first run.
# You can delete this line for the second run :)
COPY requirements.txt ${USER_CODE_PATH}/requirements.txt

RUN ${PIP} install -r ${USER_CODE_PATH}/requirements.txt

```

.env file

```
ENV=dev
PROJECT_NAME=master_project
DEFAULT_PROJECT=demo_project
```
make an empy requirements.txt

the directory structure will look like 

.
├── Dockerfile
├── docker-compose.yml
├── mage_data
├── master_project
└── requirements.txt

inside master_project create another directory "demo_project"

execute `docker compose up -d` to create test environment. In the browser navigate to http://localhost:6789/ and create a new pipeline 

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/614883/c00d51cc-8d7c-4da3-b063-ec84b98ffd5d)

### Operating system

Windows/WSL2
