### ISSUE TITLE
HelmChart  - Separated resources specification for Webserver and scheduler

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4495]
When using the helm chart is possible to specify resouces based on the following section of `values.yaml`

```
standaloneScheduler: true
....
....
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi
```

But, in this scenario both scheduler and webserver Pod (for standalone mode) use the same resouces.

I believe that would be helpful to set different resouces for scheduler and webserver, considering that websever pod requires less resouces to run than scheduler pods.

* Chart version tested: 0.2.1

Thanks!
