### ISSUE TITLE
Share main project logging_config with workspaces.

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4531]
When configuring Logging for remote logging (s3 for example), it creates a subfolder in the specifiec bucket+prefix to store the logs. The example below shows the bucket structure considering two workspaces with the same logging config

```
  | bucket/
  | - logs/
  | - - workspace1/
  | - - - pipeline1 /
  | - - - ......
  | - - workspace2 /
  | - - - pipeline1 /
  | - - - .......
```

The problem is that for doing this it's necessary to repeat the same `logging_config`  for each `metadatal.yaml` workspace file. 
```
logging_config:
    type: s3
    level: INFO
    destination_config:
      prefix: <bucket_prefix>
      aws_access_key_id: <accesskey>
      aws_secret_access_key: <secrectaccess>
      bucket: <bucket>
      endpoint_url: <url> 
``` 

In this case, would be helpful if we could set this configuration just in the main project `metadata.yaml` file. Like the example below: 

```
project_type: main

variables_dir: ~/.mage_data
# remote_variables_dir: s3://bucket/path_prefix
.....
workspace_config_defaults:
  k8s:
    service_account_name: mageai
    ingress_name: mageai
        
  logging_config:
    type: s3
    level: INFO
    destination_config:
      prefix: <bucket_prefix>
      aws_access_key_id: <accesskey>
      aws_secret_access_key: <secrectaccess>
      bucket: <bucket>
      endpoint_url: <url> 
```

In this case, we could configure the commom workspace configuration based on the main project.
