### ISSUE TITLE
[BUG] Custom design - custom design settings not being applied

### ISSUE THREAD

**Issue by ThomasGenetRepo** [mage-ai/mage-ai#4570]
### Mage version

0.9.63

### Describe the bug

The custom design I configured in the design.yaml file aren't being applied anymore since upgrading from version 0.9.62 to 0.9.63. 

### To reproduce

1. Enable 'Custom design' in the project settings
2. Copy this into the 'design.yaml' file:
```
components:
  header:
    media:
      url: https://assetsio.reedpopcdn.com/mtg-planeswalker-jace-the-mind-sculptor-artwork.jpg
```

### Expected behavior

The logo at the top left corner of the page should change to whatever the image that was linked in design.yaml. 

### Operating system

Running Mage on docker
