### ISSUE TITLE
[BUG] - MAGE_BASE_PATH no shown in HTTP trigger.

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4786]
### Mage version

0.9.63

### Describe the bug

Hello everyone. I'm using mage in kubernetes.

When configuring the environment variable MAGE_BASE_PATH , the base path is not beign appended into HTTP Trigger URL

**URL in WebBrowser**: `https://data-platform-dev.****.com/**mageai**/pipelines/inteligencia_mercado_main/triggers/6`

**URL in HTTP Trigger**: `https://data-platform-dev.****.com/api/pipeline_schedules/6/pipeline_runs/354bdc6eb04d46bdad97820ef258a094`

The URL in HTTP Trigger needs to be `https://data-platform-dev.****.com/mageai/api/pipeline_schedules/6/pipeline_runs/354bdc6eb04d46bdad97820ef258a094`

![image](https://github.com/mage-ai/mage-ai/assets/39966249/4f937cc6-e780-43d9-8d5d-79e5afea3540)

### To reproduce

Create an ingress like this

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mageai-ingress
  labels:
    name: mageai-ingress
    namespace: mage-ai
  annotations:
    nginx.ingress.kubernetes.io/path-root: /mageai
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - data-platform-dev.****.com
    secretName: dataplatform-cert-tls
  rules:
  - host: data-platform-dev.****.com
    http:
      paths:
      - pathType: Prefix
        path: /mageai
        backend:
          service:
            name: mageai
            port: 
              number: 80
```

And set the environment variable 
`MAGE_BASE_PATH: "mageai"`
