### ISSUE TITLE
[BUG] - When LoggingOut the URL does not append redirect URL

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4795]
### Mage version

0.9.63

### Describe the bug

I'm using mage-ai in kubernetes with ingress and service configuration in nginx.

When using `MAGE_BASE_PATH : mageai` and accessing the url directly, it appends the redirect URL to the correct path.

When accessing: `https://data-platform-dev.****.com/mageai/sign-in?redirect_url=%2Fmageai%2Fpipelines` it automatically append `?redirect_url=%2Fmageai%2Fpipelines` and it works. But when click in "lou out" inside the UI, it just creates the `https://data-platform-dev.neogrid.com/mageai/sign-in` and don't append the redirect URL, so the page cannot be acessed because the page is redirected to root path.

### To reproduce

Create an ingress like 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mageai-ingress
  labels:
    name: mageai-ingress
    namespace: mage-ai
  annotations:
    nginx.ingress.kubernetes.io/path-root: /mageai
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - data-platform-dev.****.com
    secretName: dataplatform-cert-tls
  rules:
  - host: data-platform-dev.****.com
    http:
      paths:
      - pathType: Prefix
        path: /mageai
        backend:
          service:
            name: mageai
            port: 
              number: 80
```

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/39966249/046baf35-6564-4f80-b50f-3e52a14928e4)
![image](https://github.com/mage-ai/mage-ai/assets/39966249/09f48fce-b4be-4326-9356-93230e3b8ffc)
