### ISSUE TITLE
Option to create HTTP Route upon Workspace creation (alternative to Ingress)

### ISSUE THREAD

**Issue by joaoferrao** [mage-ai/mage-ai#4849]
**Is your feature request related to a problem? Please describe.**
Current implementation to edit the `Ingress` upon workspace creation edits kubernetes objects that shouldn't be managed by the workspace - because they may be managed in a declarative way - in which case:
1) its state may be overridden
2) infra admins needs to find workarounds to ignore edits to the `Ingress` object after its inception.

**Describe the solution you'd like**
The backend accepts an option (e.g. `create_http_route`) as part of the workspace creation options, with proper context, to create an `HTTPRoute` object so that the workspace is immediately routable to after creation without interfering with the state of existing resources.
Much like the current implementation, this option also relies on pre-existing resources with the difference, that it doesn't change them directly.
- **Current option: Edit Existing Ingress**: `Ingress` object needs to exist prior to workspace creation and object is edited by the main workspace worker.
- **Propose solution: Create HTTPRoute**: A `Gateway` needs to exist. The main workspace worker creates an `HTTPRoute` that refers to said `Gateway` object, the hostname, name service name and the port.
Example
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
  - name: name-of-gateway
    namespace: namespace-of-gateway
  hostnames:
  - "mage.example.com"
  rules:
  - backendRefs:
    - name: workspace-svc-name
      port: 6789
```

**Describe alternatives you've considered**
The alternative is to not extend the (only) available option (editing existing Ingress) for handling the traffic/record for newly created workspaces.

**Additional context**
This request relies on the Kubernetes SIGS Gateway API: https://gateway-api.sigs.k8s.io/
Here's the simplest example of such logic (where `Gateway` needs to exist beforehand and `HTTPRoute` will be created by workspace manager): https://gateway-api.sigs.k8s.io/guides/http-routing/
