### ISSUE TITLE
[BUG] Affinity in k8s_executor_config not working

### ISSUE THREAD

**Issue by jordi-crespo** [mage-ai/mage-ai#4874]
### Mage version

0.9.68

### Describe the bug

I am trying to add tolerations and affinity to my k8s_executor_config  like this:

```
job_name_prefix: job-tes
  namespace: default
  service_account_name: mageai
  resource_limits:
    cpu: 2000m
    memory: 2000Mi
  resource_requests:
    cpu: 1000m
    memory: 1000Mi
  pod:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: job-type
              operator: In
              values:
              - spark-jobs
    tolerations:
    - key: "spark-job"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
```

the tolerations are added into the pod:

```
tolerations:
  - effect: NoSchedule
    key: spark-job
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

but the affinity is not:

```
affinity:
    nodeAffinity: {}
```

### To reproduce

1. Add affinity into the k8s_executor_config and run it in a kubernetes cluster

### Expected behavior

Affinity is added into the pod spec

### Operating system

Google Kubernetes engine

**Comment by alanxoc3** [comment]
I can confirm this issue. I'm using the latest helm release.... Bump!!

```
k8s_executor_config:
  pod:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tag
              operator: In
              values:
                - main
```

"nodeAffinity" gets populated as an empty dict with the above config.

And with this config, nodeAffinity is null in the kubernetes yaml:
```
k8s_executor_config:
  pod:
    affinity:
```

So, everything below the nodeAffinity section is ignored.

**Comment by alanxoc3** [comment]
I'll add a few notes.

I'm guessing the issue is somewhere around here. Or maybe after here. Though it isn't very obvious to me what exactly is wrong:
https://github.com/mage-ai/mage-ai/blob/master/mage_ai/services/k8s/config.py#L63-L65

I tried using underscores in the names, and it's still the same issue.

```
k8s_executor_config:
  pod:
    affinity:
      node_affinity:
        required_during_scheduling_ignored_during_execution:
          ...
```
