### ISSUE TITLE
[BUG] - MAGE_BASE_PATH not working with version 0.6.68

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4900]
### Mage version

0.6.68

### Describe the bug

Hello everyone. I've just updated the mage-ai to 0.6.68 in my docker image and the MAGE_BASE_PATH stopped to work with this version. It works with 0.6.63, but it's not working with 0.6.68. it returns "404 not found" when accessing via "addrs/MAGE_BASE_PATH".

### To reproduce

Create an ingress in kubernetes like this 

```
# Source: mageai/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mageai-externals
  namespace: mage-ai-externals
  labels:
    app.kubernetes.io/name: mageai-externals
    app.kubernetes.io/instance: mageai
  annotations:   
    kubernetes.io/elb.pass-through: "true"
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: '{"type":"inner","bandwidth_name":"cce-bandwidth","bandwidth_chargemode":"bandwidth","bandwidth_size":5,"bandwidth_sharetype":"PER","eip_type":"5_bgp","name":"mage-ai-externals"}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 6789
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mageai-webservice-externals
    app.kubernetes.io/instance: mageai

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mageai-externals-ingress
  labels:
    name: mageai-externals-ingress
    namespace: mage-ai-externals
  annotations:
    nginx.ingress.kubernetes.io/path-root: /mageai-staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hostaddress.com
    secretName: dataplatform-cert-tls
  rules:
  - host: data-platform-dev.neogrid.com
    http:
      paths:
      - pathType: Prefix
        path: /mageai-staging
        backend:
          service:
            name: mageai-externals
            port: 
              number: 80
```
