### ISSUE TITLE
[BUG] - Kafka authentication "check_hostname" false is not beign applied.

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#5031]
### Mage version

0.9.70

### Describe the bug

I'm trying to authenticate Kafka within a streaming pipeline like this:
```
connector_type: kafka
# bootstrap_server: "{{ env_var('DATAPLATFORM01_KAFKA_SERVERS') }}" 
topic: visibilidade-direto.transient-ingestion
consumer_group: mage-to-hwc-kafka-listener
include_metadata: false
api_version: 0.10.2

# Uncomment the config below to use SSL config
# security_protocol: "SSL"
# ssl_config:
#   cafile: "/etc/kafka/ssl/ca.pem"
#   # certfile: "/etc/kafka/ssl/cert.pem"
#   # keyfile: "/etc/kafka/ssl/key.pem"
#   # password: "{{ env_var('KAFKA_PASSWORD') }}"
#   check_hostname: false

# Uncomment the config below to use SASL_SSL config
security_protocol: "SASL_SSL"
sasl_config:
  mechanism: "PLAIN"
  username: "{{ env_var('KAFKA_USERNAME') }}"
  password: "{{ env_var('KAFKA_PASSWORD') }}"
ssl_config:
  cafile: "/etc/kafka/ssl/ca.pem"
  certfile: "/etc/kafka/ssl/cert.pem"
  keyfile: "/etc/kafka/ssl/key.pem"
  password: "{{ env_var('KAFKA_PASSWORD') }}"
  check_hostname: false
```

But when running the pipeline it's not matching the ssl certificate.
![image](https://github.com/mage-ai/mage-ai/assets/39966249/02fef9e6-2398-47d7-a2c7-a3db442c8c7f)

When trying to verify the handshake in the pod it works.
`openssl s_client -connect <broker_ip> -CAfile /etc/kafka/ssl/ca.pem -cert /etc/kafka/ssl/cert.pem -key /etc/kafka/ssl/key.pem -showcerts`

![image](https://github.com/mage-ai/mage-ai/assets/39966249/a57bdbb9-594c-4800-af8a-d3deba9dcb60)
