### ISSUE TITLE
Allow for multiple connections to same type of Source/Destination

### ISSUE THREAD

**Issue by manucorrado-lodgify** [mage-ai/mage-ai#5109]
**Is your feature request related to a problem? Please describe.**
As the number of pipelines increases, the number of connections to same-type Sources and Destinations also increases.
For example we can have 10+ connections to PostgreSQL, MSSQL & BigQuery. As of now you would need a **minimum of 10 io_config.yaml profiles** to work with this. This come become unnecessarily complex and hard to maintain.

**Describe the solution you'd like**
A workaround that would make this easier and improve on QoL would look like this:
**io_config.yaml**
```
test_connections:
  read_user_postgres:
    POSTGRES_READ_CONNECT_TIMEOUT: 10
    POSTGRES_READ_DBNAME: dbname
    POSTGRES_READ_SCHEMA: public # Optional
    POSTGRES_READ_USER: "{{ mage_secret_var('test_read_user') }}"
    POSTGRES_READ_PASSWORD: "{{ mage_secret_var('test_password') }}"
    POSTGRES_READ_HOST: 1.1.1.1
    POSTGRES_READ_PORT: 5432
  write_user_postgres:
    POSTGRES_WRITE_CONNECT_TIMEOUT: 10
    POSTGRES_WRITE_DBNAME: second_db_name
    POSTGRES_WRITE_USER: "{{ mage_secret_var('test_write_user') }}"
    POSTGRES_WRITE_PASSWORD: "{{ mage_secret_var('test_write_password') }}"
    POSTGRES_WRITE_HOST: 1.0.0.0
    POSTGRES_WRITE_PORT: 5432
```

Then in your blocks you can easily select which _sub-profile_ to choose within **test_connections** as follows:

**BLOCK 1**
```
    config_profile = 'test_connections.read_user_postgres'
    
    with Postgres.with_config(ConfigFileLoader(config_path, config_profile)) as loader:
        return loader.load(query)
```

**BLOCK 2**
```
    config_profile = 'test_connections.write_user_postgres'
    
    with Postgres.with_config(ConfigFileLoader(config_path, config_profile)) as loader:
        return loader.load(query)
```
