### ISSUE TITLE
[BUG] Can not run block with ECS excutor when assign_public_ip is set to false

### ISSUE THREAD

**Issue by kelvin-rennlabs** [mage-ai/mage-ai#5119]
### Mage version

0.9.70

### Describe the bug

I set the block to run using ECS executor like this:

```
- all_upstream_blocks_executed: true
  color: grey
  configuration: {}
  downstream_blocks: []
  executor_config:
    cpu: 1024
    memory: 2048
    assign_public_ip: false
    enable_execute_command: true
    executor_type: ecs
```
The pipeline remained running when assign_public_ip was set to false. However, the pipeline ran without issues after changing the value to true.

### Screenshots

![Screenshot 2024-05-27 at 23 24 13](https://github.com/mage-ai/mage-ai/assets/136250146/d0276a25-f2e7-425f-8c43-d1ad2337ae75)

### Operating system

- OS: MacOS
- Browser: Chrome
