### ISSUE TITLE
[BUG] workspace_config_defaults are not applied as expected

### ISSUE THREAD

**Issue by MartinLoeper** [mage-ai/mage-ai#5198]
### Mage version

0.9.71

### Describe the bug

I defined the `workspace_config_defaults -> lifecycle_config` but none of those values seem to be applied, see screenshot.

### To reproduce

1. Create metadata.yaml with content:
```yaml
workspace_config_defaults:
  lifecycle_config:
    pre_start_script_path: pre-start.py
    termination_policy:
      enable_auto_termination: true
      max_idle_seconds: 3600
```
2. Create New Workspace
3. Extend the Lifecycle (Optional) pane

### Expected behavior

I expect my defaults to be applied. They seem to be ignored.

### Screenshots

![Screenshot from 2024-06-18 12-45-32](https://github.com/mage-ai/mage-ai/assets/5209395/dc08bbe0-80e6-4d18-9cd9-d41f0a2aef6c)
![Screenshot from 2024-06-18 12-46-15](https://github.com/mage-ai/mage-ai/assets/5209395/ddffaf59-7a99-4cfe-8062-3f6ca806273f)

### Operating system

- OS: Linux (NixOS)
- Browser: Google Chrome
