### ISSUE TITLE
[BUG] Block has 'running' status after completion when output has many elements

### ISSUE THREAD

**Issue by victorregism** [mage-ai/mage-ai#5244]
### Mage version

0.9.71

### Describe the bug

When running a block containing an output that Mage breaks down into multiple sub outputs, the status of this block gets stuck as 'running' even though the block has completed the execution. The pipeline execution can't continue

### To reproduce

1. Create a pipeline
2. Add two blocks and connect them
3. On the first block of the pipeline, add the following code in the main function
```
data = [0]*100000
return data
```
4. Trigger pipeline execution

### Expected behavior

Pipeline finishes without any issues

### Screenshots

<img width="844" alt="Captura de Tela 2024-07-02 às 11 55 39" src="https://github.com/mage-ai/mage-ai/assets/160499790/f0918dff-9c43-4a5b-ba3e-0b891429763e">
<img width="1406" alt="Captura de Tela 2024-07-02 às 12 00 04" src="https://github.com/mage-ai/mage-ai/assets/160499790/e9370ca7-12b1-4ad1-b869-d199609e5941">
<img width="841" alt="Captura de Tela 2024-07-02 às 12 11 54" src="https://github.com/mage-ai/mage-ai/assets/160499790/c8232e22-b776-44c3-aa90-efa2ac7f0d70">
<img width="1450" alt="Captura de Tela 2024-07-02 às 12 11 43" src="https://github.com/mage-ai/mage-ai/assets/160499790/6f4abe8d-0945-4cd2-8ca4-d27b1d12e48e">

### Operating system

3 Kubernetes Pods for webserver and 3 for scheduler where

Webserver manifesto has:
```
resources:
            limits:
              cpu: 4500m
              memory: 4500Mi
            requests:
              cpu: 4000m
              memory: 4000Mi
          env:
```
Scheduler manifesto has:
```
resources:
            limits:
              cpu: 8500m
              memory: 16500Mi
            requests:
              cpu: 8000m
              memory: 16000Mi
```

### Additional context

- I also included an example (2 last screenshots) where each element in the list was a dict (two keys id and content and values 0 to both)and the behavior was the same, except that in the 'outputs' tab I had output, output2A, and etc, which indicates to me that the block is treating each list element as a different output
- Wrapping the list in another list or tuple (where the big list is the sole element) solves this issue
- Tested with transformer, loader and custom blocks as the first block of the pipeline
