### ISSUE TITLE
[BUG] module 'builtins' has no attribute 'NoneType'

### ISSUE THREAD

**Issue by kaikiat** [mage-ai/mage-ai#5282]
### Mage version

v0.9.72

### Describe the bug

Pipeline suddenly not showing. The error message is 

```
module 'builtins' has no attribute 'NoneType
```
<img width="1032" alt="Screenshot 2024-07-20 at 10 44 55 PM" src="https://github.com/user-attachments/assets/fffba49b-5d5e-4698-88af-f85345970c3e">

Stack trace

<img width="1042" alt="Screenshot 2024-07-20 at 10 45 47 PM" src="https://github.com/user-attachments/assets/d7b1eb20-c989-4dfb-bfa8-80c382693022">

This is my metadata.yaml

```
# /pipelines/gsheet_dump/metadata.yaml
blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: extract_tutor
  retry_config: null
  status: executed
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: extract_tutor
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-07-18 14:59:59.088268+00:00'
data_integration: null
description: Gsheet pipeline and stuff
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: gsheet_dump
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: gsheet_dump
variables_dir: /Users/kaikiat/.mage_data/pipelines
widgets: []
```

### Screenshots
<img width="1417" alt="Screenshot 2024-07-20 at 10 43 04 PM" src="https://github.com/user-attachments/assets/e7f7678d-b796-4fbb-a5aa-fac947477b14">

### Operating system

- macos m2 , microsoft edge, python 3.11, url: http://localhost:6789/pipelines/gsheet_dump/edit?sideview=tree
