### ISSUE TITLE
[BUG] Can't define usage of reserved words on streaming data export

### ISSUE THREAD

**Issue by MatheusAnciloto** [mage-ai/mage-ai#5288]
### Mage version

0.9.72

### Describe the bug

I have a streaming pipeline that receives kafka messages, transforms it and then it goes to a postgres data exporter block (which is configured only with the yaml file).

Similar to other issues reported here I'm using some columns that it tries to change, for example `timestamp` throws this error:

```psycopg2.errors.UndefinedColumn: column "_timestamp" of relation "transactions" does not exist```

I tried to include `allow_reserved_words: true` in the yaml but I get: ```TypeError: PostgresConfig.__init__() got an unexpected keyword argument 'allow_reserved_words'```

Is there a way for me to still use this words in this setup?

**Comment by JJJ000** [comment]
@MatheusAnciloto I am working on a fix, could you share your config of both kafka and postgres, I am trying to reproduce the error.

**Comment by MatheusAnciloto** [comment]
@JJJ000 Thanks for the reply, so in my case I did change my table columns and the name exported in my transformer

Data loader:

```
connector_type: kafka
bootstrap_server: CLUSTER_URL
topic: KAFKA_TOPIC
consumer_group: mage_group
include_metadata: false
api_version: 2.6.0
auto_offset_reset: latest
security_protocol: SASL_SSL
sasl_config:
  mechanism: PLAIN
  username: user
  password: *******
ssl_config:
  cafile: /mage_data/cafile.crt
serde_config:
  serialization_method: RAW_VALUE
```

Data exporter:

```
connector_type: postgres
database: DB_NAME
host: DB_HOST
username: DB_USER
password: DB_PASSWORD
port: "5432"
schema: public
table: DB_TABLE
unique_conflict_method: DO NOTHING
unique_constraints:
  - id
```

The above is my current data exporter with the column names not being a reserved word, I tried to include a `allow_reserved_words: true` but it didn't work at the time I tried
