### ISSUE TITLE
[BUG] 404 on frontend https://url/api/file_contents/default_repo...

### ISSUE THREAD

**Issue by jicao** [mage-ai/mage-ai#5303]
### Mage version

 0.9.72

### Describe the bug

Got 404 errors on files frontend like:
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fio_config.yaml?api_key=xxx404 (Not Found)
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fmetadata.yaml?api_key=xxx404 (Not Found)
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fdata_loaders%2Fload_titanic.py?api_key=xxx404 (Not Found)
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fio_config.yaml?api_key=xxx404 (Not Found)
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fmetadata.yaml?api_key=xxx2 404 (Not Found)
>        GET https://mageai.url.tld/api/file_contents/default_repo%2Fdata_loaders%2Fload_titanic.py?api_key=xxx 404 (Not Found)

### To reproduce

I installed Mage with Docker with this Stack
```
version: "3.3"
services:
    postgres:
        image: elestio/postgres:latest
        restart: always
        volumes:
            - '/home/xxx/mage-ai-data/pgdata:/var/lib/postgresql/data'
        environment:
            - POSTGRES_USER=mageai
            - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
            - POSTGRES_DB=mageai
            - PG_DATA=/var/lib/postgresql/data/pgdata

    mage:
        image: elestio/mage-ai:latest
        restart: always
        environment:
            - REQUIRE_USER_AUTHENTICATION=1
            - DEFAULT_OWNER_EMAIL=xxx@xxx.xxx
            - DEFAULT_OWNER_PASSWORD=xxx
            - DEFAULT_OWNER_USERNAME=xxx@xxx.xxx
        volumes:
            - '/home/xxx/mage-ai-data/data:/home/src'
            - '/home/xxx/mage-ai-data/mage_data:/root/.mage_data'
        ports:
            - 6789:6789
```
And I setup an Apache proxy like this
```
    SSLProxyEngine on
    ProxyRequests Off
    ProxyPass / http://xxx.xxx.xxx.xxx:6789/
    ProxyPassReverse / http://xxx.xxx.xxx.xxx:6789/

    ProxyVia on

    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://xxx.xxx.xxx.xxx:6789/$1 [P,L]

    ProxyPass               /websocket http://xxx.xxx.xxx.xxx:6789/websocket
    ProxyPassReverse        /websocket http://xxx.xxx.xxx.xxx:6789/websocket
```

### Expected behavior

Nothing more than edit files :)

### Operating system

Ubuntu 22.04 LTS
Chrome Version 126.0.6478.183 (64 bits)

### Additional context

Thanks a lot for your help
