### ISSUE TITLE
[BUG] Pipelines stuck due to high CPU usage of Mage scheduler

### ISSUE THREAD

**Issue by sugimiyanto** [mage-ai/mage-ai#5345]
### Mage version

0.9.73

### Describe the bug

I have issues with the pipeline schedules that are not triggered, pipelines stuck in `Ready` and `Running` after I downgraded my database spec (CPU & memory). The database contains Mage's database.
Prior to downgrading, everything was ok.
- I checked through /api/status, the scheduler is running.
- I deployed Mage in on-prem Docker
- I have to restart the container (created a kind of healthcheck) every time it got stuck due to high CPU usage of container

CPU usage history:
![image](https://github.com/user-attachments/assets/8b351ef1-3a3d-467c-af64-f9ac274ba7a8)

### To reproduce

1. Setup Mage using docker on-prem with postgres as the backbone database
2. Setup some schedules to run a simple pipeline
3. Downgrade the postgres database spec i.e. CPU and memory
4. See an anomaly that the CPU usage is rising after some times even there is no pipeline running at the time

### Expected behavior

Mage can still run properly with normal resource usage after database down/up-grading

### Operating system

OS: Linux CentOS 7.6.1810

### Additional context

My docker-compose.yaml
```yaml
version: '3'
services:
  mage-webserver:
    container_name: mage-webserver
    image: mageai/mageai:0.9.73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REQUIRE_USER_AUTHENTICATION: 1
      MAGE_DATABASE_CONNECTION_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DBNAME}"
      MAGE_ACCESS_TOKEN_EXPIRY_TIME: 86400
      REDIS_URL: resid://redis:6379/0
    ports:
      - "6789:6789"
    command: |
      /bin/sh -c "
      mage start ${PROJECT_NAME}" --instance-type web_server
    depends_on:
      - redis

  mage-scheduler:
    container_name: mage-scheduler
    image: mageai/mageai:0.9.73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MAGE_DATABASE_CONNECTION_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DBNAME}"
      MAGE_ACCESS_TOKEN_EXPIRY_TIME: 86400 # 24 hours
      REDIS_URL: resid://redis:6379/0
    command: |
      mage start ${PROJECT_NAME}" --instance-type scheduler
    depends_on:
      - redis
  
  redis:
    image: redis:7.4.0
```

Running processes inside container:
```
root@e9557bb890bb:/home/src# ps auxw
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mage         21  0.6  0.7 3635180 466464 ?      Sl   08:53   0:31 /usr/local/bin/python /usr/local/bin/mage start etl_platform_mage
mage         55  0.0  0.3 2112488 244004 ?      Sl   08:53   0:00 /usr/local/bin/python /usr/local/bin/mage start etl_platform_mage
mage         67  0.0  0.0 746068 53180 ?        Ssl  08:53   0:01 /usr/local/bin/python -m ipykernel_launcher -f /tmp/tmpi3s4cdej.json
root        107  0.0  0.0   4592  2424 pts/0    Ss+  08:54   0:00 /bin/bash
mage       1074 71.7  0.7 3264444 475264 ?      Rl   09:41  22:49 /usr/local/bin/python /usr/local/bin/mage start etl_platform_mage
mage       1076  0.0  0.0   4592  2356 pts/1    Ss+  09:41   0:01 /usr/bin/bash
mage       1249  0.0  0.6 3193024 401620 ?      S    09:43   0:00 /usr/local/bin/python /usr/local/bin/mage start etl_platform_mage
mage       1315 97.8  0.6 3192000 403816 ?      R    09:48  24:44 /usr/local/bin/python /usr/local/bin/mage start etl_platform_mage
mage       1446  0.0  0.0      0     0 ?        Z    09:48   0:00 [python3] <defunct>
root       1486  0.0  0.0   4592  2368 pts/2    Ss   10:07   0:00 /bin/bash
root       1516  0.0  0.0   8516  2960 pts/2    R+   10:13   0:00 ps auxw
```

`/api/status` response:
```json
{
  "statuses": [
    {
      "is_instance_manager": false,
      "max_print_output_lines": 1000,
      "repo_path": "/home/src/etl_platform_mage",
      "repo_path_relative": "etl_platform_mage",
      "repo_path_relative_root": "etl_platform_mage",
      "repo_path_root": "/home/src/etl_platform_mage",
      "server_process_id": 21,
      "scheduler_process_id": 1074,
      "scheduler_status": "running",
      "instance_type": null,
      "disable_pipeline_edit_access": false,
      "require_user_authentication": false,
      "require_user_permissions": false,
      "project_type": "standalone",
      "project_uuid": "fd1a818432ce49e887f9aac406bd5233"
    }
  ],
  "metadata": {

  }
}
```

Mage scheduler's process profiling (recorded when the CPU usage is high)
![profile](https://github.com/user-attachments/assets/096e3c97-c173-4422-94c6-73219b024bee)

Discussion on slack:
https://mageai.slack.com/archives/C03HTTWFEKE/p1722912825470399
