### ISSUE TITLE
[BUG] Facebook ad integration need to be version v20.0 or higher

### ISSUE THREAD

**Issue by bachkukkik** [mage-ai/mage-ai#5384]
### Mage version

0.9.73

### Describe the bug

vanilla mageai version 0.9.73 gave me this error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1662, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1564, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1904, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/integration/__init__.py", line 159, in _execute_block
    print_log_from_line(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/logger/utils.py", line 83, in print_log_from_line
    raise Exception(message)
Exception: **********T07:38:17 FacebookAds process failed with error SingerSyncError
POST: 400 Message: (#2635) You are calling a deprecated version of the Ads API. Please upgrade to the latest version: v20.0.. {"error": "SingerSyncError
POST: 400 Message: (#2635) You are calling a deprecated version of the Ads API. Please upgrade to the latest version: v20.0.", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/facebook_ads/__init__.py\", line 45, in <module>
    main(FacebookAds, schemas_folder='tap_facebook/schemas')
", "  File \"/usr/local/lib/python3.10/site-packages/singer/utils.py\", line 235, in wrapped
    return fnc(*args, **kwargs)
", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 732, in main
    source.process()
", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 281, in process
    errors=traceback.format_stack(),
"], "message": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py\", line 1000, in do_sync_with_except
    do_sync(account, catalog, state, logger=logger)
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py\", line 866, in do_sync
    for message in stream:
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py\", line 756, in __iter__
    job = self.run_job(params)
  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry
    ret = target(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/backoff/_sync.py\", line 105, in retry
    ret = target(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/facebook_ads/tap_facebook/__init__.py\", line 715, in run_job
    job = self.account.get_insights(  # pylint: disable=no-member
  File \"/usr/local/lib/python3.10/site-packages/facebook_business/adobjects/adaccount.py\", line 2871, in get_insights
    return self.get_insights_async(fields, params, batch, success, failure, pending)
  File \"/usr/local/lib/python3.10/site-packages/facebook_business/adobjects/adaccount.py\", line 2990, in get_insights_async
    return request.execute()
  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 682, in execute
    response = self._api.call(
  File \"/usr/local/lib/python3.10/site-packages/facebook_business/api.py\", line 350, in call
    raise fb_response.error()
facebook_business.exceptions.FacebookRequestError: 
  Message: Call was not successful
  Method:  POST
  Path:    https://graph.facebook.com/v17.0/act_*****************/insights
  Params:  {'level': 'ad', 'action_breakdowns': '[\"action_type\",\"action_target_id\",\"action_destination\"]', 'breakdowns': '[\"age\",\"gender\"]', 'limit': 100, 'fields': '[\"engagement_rate_ranking\",\"adset_id\",\"reach\",\"cpm\",\"adset_name\",\"canvas_avg_view_time\",\"campaign_name\",\"ad_name\",\"social_spend\",\"unique_clicks\",\"actions\",\"objective\",\"cost_per_inline_post_engagement\",\"unique_inline_link_clicks\",\"video_p25_watched_actions\",\"ctr\",\"cpc\",\"impressions\",\"conversion_rate_ranking\",\"cost_per_unique_action_type\",\"inline_link_click_ctr\",\"cost_per_action_type\",\"cost_per_inline_link_click\",\"unique_ctr\",\"clicks\",\"website_ctr\",\"unique_actions\",\"unique_outbound_clicks\",\"ad_id\",\"cost_per_unique_inline_link_click\",\"account_name\",\"inline_post_engagement\",\"frequency\",\"campaign_id\",\"video_p75_watched_actions\",\"cpp\",\"action_values\",\"inline_link_clicks\",\"cost_per_unique_click\",\"video_p100_watched_actions\",\"unique_inline_link_click_ctr\",\"video_p50_watched_actions\",\"quality_ranking\",\"unique_link_clicks_ctr\",\"account_id\",\"date_stop\",\"canvas_avg_view_percent\",\"video_play_curve_actions\",\"spend\",\"outbound_clicks\",\"video_30_sec_watched_actions\",\"date_start\"]', 'time_increment': 1, 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'time_ranges': '[{\"since\":\"2024-08-07\",\"until\":\"2024-08-07\"}]'}
  Status:  400
  Response:
    {
      \"error\": {
        \"message\": \"(#2635) You are calling a deprecated version of the Ads API. Please upgrade to the latest version: v20.0.\",
        \"type\": \"OAuthException\",
        \"code\": 2635,
        \"fbtrace_id\": \"xxxx\"
      }
    }
```

my quick fix is to add `facebook_business==20.0.2` to custom requirements.txt
just upgrade a package then the pipeline can go through

below is my docker-compose.yml mage.ai setup

```yaml
mageai_base: 
  image: mageai/mageai:latest
  environment:
    REQUIRE_USER_AUTHENTICATION: 1
    MAGE_DATABASE_CONNECTION_URL: "postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-P@ssw0rd}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}"
    REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/1
    GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ULIMIT_NO_FILE: 65536
  command:
    - -c
    - |
      pip install --no-deps -r ./${MAGEAI_PROJECT_NAME}/requirements.txt
      /app/run_app.sh mage start ${MAGEAI_PROJECT_NAME}
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:6789"]
    interval: 5s
    timeout: 5s
    retries: 10
  restart: unless-stopped
  networks:
    - default
```

### To reproduce

1. setup facebook data loader with integration pipeline block
2. try running using trigger once
3. observe the log
