### ISSUE TITLE
[BUG] Automatic retry does not work for backfills

### ISSUE THREAD

**Issue by HMaker** [mage-ai/mage-ai#5448]
### Mage version

0.9.73

### Describe the bug

Pipeline automatic retry is not applied to its backfills.

### To reproduce

Create a pipeline with the following `metadata.yml`
```yml
blocks:
- all_upstream_blocks_executed: true
  color: null
  configuration: {}
  downstream_blocks:
  - mellow_glacier
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: elven sword
  retry_config: null
  status: updated
  timeout: null
  type: data_loader
  upstream_blocks: []
  uuid: elven_sword
- all_upstream_blocks_executed: false
  color: null
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: mellow glacier
  retry_config: null
  status: updated
  timeout: null
  type: data_exporter
  upstream_blocks:
  - elven_sword
  uuid: mellow_glacier
cache_block_output_in_memory: false
callbacks: []
concurrency_config:
  on_pipeline_run_limit_reached: wait
  pipeline_run_limit_all_triggers: 1
conditionals: []
created_at: '2024-09-25 23:09:53.394466+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: test_backfill_retry
notification_config: {}
remote_variables_dir: null
retry_config:
  delay: 3
  max_delay: 3
  retries: 10
run_pipeline_in_one_process: true
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: test_backfill_retry
variables_dir: /home/src/mage_data/pipelines
widgets: []
```
Create a data loader block named `elven_sword` with the following source code
```py
if 'data_loader' not in globals():
    from mage_ai.data_preparation.decorators import data_loader
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test


@data_loader
def load_data_from_api(*args, **kwargs):
    logger = kwargs.get("logger")
    logger.info("running data loader block...")
    return []
```
Create a data exporter block named `mellow_glacier` with the following source code
```py
if 'data_exporter' not in globals():
    from mage_ai.data_preparation.decorators import data_exporter


@data_exporter
def export_data_to_file(data, **kwargs) -> None:
    logger = kwargs.get("logger")
    logger.info("running data exporter block...")
    raise Exception("injected exception into the data exporter block")
```
Make sure `elven_sword``is the upstream block of `mellow_glacier`.
Create a datetime backfill for that pipeline and start it.

### Expected behavior

I should see retry logs from the backfill run, it should print `"running data exporter block..."` multiple times, one for each retry.

Also the pipeline logs list does not show any retry.

### Operating system

OS Ubuntu 20.04 with Google Chrome 128
