### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wesseldr** [mage-ai/mage-ai#5514]
### Mage version

v0.9.74

### Describe the bug

Using the MongDB connection string still needs a MONGODB_DATABSE env to work else it fails.

### To reproduce

inside the io_config.yaml create an entry for mongoDB that uses SHA-1

```yaml
mv_prod:

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://reporting:{{ mage_secret_var('reporting_secret') }}@10.0.0.1:27017/my_database?authSource=my_database&authMechanism=SCRAM-SHA-1"
  #MONGODB_DATABASE: my_database

```
create a versions collection inside the my_database with some content in it.

use the following data Loader block:
```python
@data_loader
def load_from_mongodb(*args, **kwargs):
    config_path = path.join(get_repo_path(), 'io_config.yaml')
    config_profile = 'mv_prod'

    query = {}

    return MongoDB.with_config(ConfigFileLoader(config_path, config_profile)).load(
        query=query,
        collection='versions'
    )
```

Running the data_loader block fails with the error:
```json
File /usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py:1550, in MongoClient.__getitem__(self, name)
   1541 def __getitem__(self, name: str) -> database.Database[_DocumentType]:
   1542     """Get a database by name.
   1543 
   1544     Raises :class:`~pymongo.errors.InvalidName` if an invalid
   (...)
   1548       - `name`: the name of the database to get
   1549     """
-> 1550     return database.Database(self, name)

File /usr/local/lib/python3.10/site-packages/pymongo/database.py:134, in Database.__init__(self, client, name, codec_options, read_preference, write_concern, read_concern)
    126 super(Database, self).__init__(
    127     codec_options or client.codec_options,
    128     read_preference or client.read_preference,
    129     write_concern or client.write_concern,
    130     read_concern or client.read_concern,
    131 )
    133 if not isinstance(name, str):
--> 134     raise TypeError("name must be an instance of str")
    136 if name != "$external":
    137     _check_name(name)

TypeError: name must be an instance of str
```

Now uncomment the line from io_config.yaml that has: 
```
#MONGODB_DATABASE: my_database
```

This should read now:
```yaml

mv_prod:

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://reporting:{{ mage_secret_var('reporting_secret') }}@10.0.0.1:27017/my_database?authSource=my_database&authMechanism=SCRAM-SHA-1"
  MONGODB_DATABASE: my_database
```

Run the loader block again and it will execute correctly with no errors

### Expected behavior

Both configs should work and not throw an error.

```yaml
mv_prod:

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://reporting:{{ mage_secret_var('reporting_secret') }}@10.0.0.1:27017/my_database?authSource=my_database&authMechanism=SCRAM-SHA-1"
  #MONGODB_DATABASE: my_database

```

and
 
```yaml
mv_prod:

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://reporting:{{ mage_secret_var('reporting_secret') }}@10.0.0.1:27017/my_database?authSource=my_database&authMechanism=SCRAM-SHA-1"
  MONGODB_DATABASE: my_database

```

### Operating system

Official Docker mageai/mageai:latest
sha256:bc0754c0473
