### ISSUE TITLE
[BUG] Teams notifications' title is not read from config

### ISSUE THREAD

**Issue by ilariacestari** [mage-ai/mage-ai#5784]
### Mage version

0.9.76

### Describe the bug

In `sender.py`, the notification's title for Teams is not pass as parameter to `send_teams_message`, thus the notifications' title cannot be override from configuration and still show the default one: "Mage pipeline run status logs"

### To reproduce

1. In `metadata.yaml` add notification config for Teams
```yaml
notification_config:
  alert_on:
  - trigger_failure
  - trigger_passed_sla
  - trigger_success
  teams_config:
    webhook_url: "{{ env_var('MAGE_TEAMS_WEBHOOK_URL') }}"
  message_templates:
    success:
      title: "My custom title"
      summary: "My custom summary"
```
2. Run a pipeline

### Expected behavior

Title and summary of the notification should show the same text defined in config

### Screenshots

Current behavior
![Image](https://github.com/user-attachments/assets/4adea350-e7f6-473d-acea-341f04dd2d4e)
