### ISSUE TITLE
[BUG] Use the sample configuration in the document to run the variables and open the task page to report an error

### ISSUE THREAD

**Issue by 13129** [mage-ai/mage-ai#5791]
### Mage version

0.9.75

### Describe the bug

![Image](https://github.com/user-attachments/assets/c3df8656-20fd-4369-8e06-88a8e7e82d1d)

```
variables:
   Sharedvar1: value1
   sharedvar2: value2
   dev:
      var: value1
   staging:
      var: value2
   prod:
      var: value3
```

![Image](https://github.com/user-attachments/assets/6a9477e9-dbe0-4265-be6a-a874cf6a09e0)
**Objects are not valid as a React child (found: object with keys {var}). If you meant to render a collection of children, use an array instead.**
