### ISSUE TITLE
[BUG] Non-ASCII characters in text[] columns lose their encoding when exporting to Postgres

### ISSUE THREAD

**Issue by nacer-benyoub** [mage-ai/mage-ai#5803]
### Mage version

0.9.76

### Describe the bug

Columns of type `text[]` with non-ASCII characters are incorrectly encoded (`é` → `u00e9`, `ï` → `u00ef`) after being exported to Postgres

### To reproduce

1. Start a Mage instance with a Postgres database. example `docker-compose.yml` file:
```yaml
services:
  magic:
    image: mageai/mageai:0.9.76
    command: mage start demo
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
  postgres:
    image: postgres:17
    restart: on-failure
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
```
3. Create a new pipeline.
4. In the notebook, create a Python data loader block and a SQL data exporter block (Postgres) that depends on it (loader → exporter).
5. In the loader block, create a dataframe that has one value as an array of strings with non-ASCII characters. e.g., `["éxtension", "aller à l'école"]`. For example:
```python
data = {"val": [["éxtension", "aller à l'école"]]}
df = pd.DataFrame(data)
```
6. In the exporter block, inspect `{{ df_1 }}`
```sql
SELECT * FROM {{ df_1 }}
```
You'll find that non-ASCII characters are improperly encoded. Therefore, the earlier array becomes `["u00e9xtension", "aller u00e0 l'u00e9cole"]`

### Expected behavior

Non-ASCII characters in columns of type array of string or `text[]` should maintain their encoding when exported to Postgres.

### Screenshots

![Image](https://github.com/user-attachments/assets/b0b417dd-8cec-4bb9-8536-dd3cc41515b8)
